# Generated by Django 3.0.4 on 2020-03-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
