# Generated by Django 3.0.4 on 2020-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200311_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialinstance',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
